[project]
name = "hw1-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "modelscope>=1.26.0",
    "transformers>=4.52.4",
    "vllm>=0.9.0.1",
]
